import Image from "next/image";
import Link from "next/link";
import type { SVGProps } from "react";
type IconProps = SVGProps<SVGSVGElement>;
function ItemsCube() { return <svg className="items-cube" viewBox="0 0 180 180" fill="none" stroke="#000" strokeWidth="5" strokeLinejoin="round" aria-hidden="true"><polygon points="90,22 145,52 90,82 35,52" /><polygon points="35,52 90,82 90,145 35,115" /><polygon points="145,52 90,82 90,145 145,115" /></svg>; }
function FluidOutlineIcon() { return <svg className="fluid-category-icon" viewBox="0 0 180 180" fill="none" aria-hidden="true"><path d="M90 24S54 67 54 98c0 20 16 38 36 38s36-18 36-38c0-31-36-74-36-74Z" stroke="#000" strokeWidth="6" strokeLinejoin="round" /><path d="M75 101c4 9 11 13 19 15" stroke="#000" strokeWidth="6" strokeLinecap="round" /></svg>; }
function QuestionIcon() { return <svg className="question-category-icon" viewBox="0 0 180 180" fill="none" aria-hidden="true"><circle cx="90" cy="90" r="52" stroke="currentColor" strokeWidth="6" /><path d="M74 70c0-12 8-20 20-20s20 8 20 18c0 10-6 16-15 22-7 4-9 8-9 14" stroke="currentColor" strokeWidth="6" strokeLinecap="round" strokeLinejoin="round" /><circle cx="90" cy="124" r="5" fill="currentColor" /></svg>; }
function BookIcon(props: IconProps) { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}><path d="M5 5.5A2.5 2.5 0 0 1 7.5 3H19v16H7.5A2.5 2.5 0 0 0 5 21ZM5 5.5V21M9 7h6" /></svg>; }
function ProgressIcon(props: IconProps) { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}><path d="M4 18h16M7 18V9M12 18V6M17 18v-4" /></svg>; }
function RecipeIcon(props: IconProps) { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}><rect x="4" y="4" width="16" height="16" rx="2" /><path d="M8 8h8M8 12h8M8 16h5" /></svg>; }
const quickLinks = [
  { Icon: BookIcon, title: "Machines", text: "Browse every machine documented for 0.0.5-B.", href: "/wiki/machines" },
  { Icon: ProgressIcon, title: "Items", text: "Materials, components, equipment and block items.", href: "/wiki/items" },
  { Icon: RecipeIcon, title: "Fluids", text: "Browse the complete 0.0.5-B fluid catalog.", href: "/wiki/fluids" },
];
export default function Home() { return <main>
  <header className="topbar"><a className="brand" href="#" aria-label="HBM Wiki home"><Image className="brand-logo" src="/logo-main.png" alt="HBM's NTM NeoForge Edition logo" width={160} height={120} priority /><span><strong>HBM&apos;s Nuclear Tech Mod</strong><small>Unofficial NeoForge Edition Wiki</small></span></a><nav className="nav"><a href="#wiki">Wiki</a><a href="#guides">Browse</a><a href="https://github.com/YellowYotu/hbm_neoforge-1.21.1" target="_blank" rel="noreferrer">GitHub</a><a href="https://discord.gg/A9NK8xypwU" target="_blank" rel="noreferrer">Discord</a></nav></header>
  <section className="hero"><div className="hazard-strip" /><div className="hero-inner"><div className="hero-logo-wrap"><Image className="hero-logo" src="/logo-main.png" alt="HBM's NTM NeoForge Edition logo" width={1536} height={1158} priority /></div><div className="hero-copy"><span className="eyebrow">Official Wiki</span><h1>HBM&apos;s Nuclear Tech Mod</h1><h2>Unofficial NeoForge Edition</h2><p>Wiki for the released 0.0.5-B content on Minecraft 1.21.1 NeoForge. Machines, items and fluids are documented now; unreleased systems stay marked as Coming Soon.</p><div className="hero-actions"><a className="primary-button" href="#wiki">Browse Wiki</a><a className="secondary-button" href="https://github.com/YellowYotu/hbm_neoforge-1.21.1" target="_blank" rel="noreferrer">Source Code</a></div><div className="version-row"><span>0.0.5-B</span><span>Minecraft 1.21.1</span><span>NeoForge</span><span>By YellowYotu</span></div></div></div></section>
  <section className="section" id="wiki"><div className="section-heading"><div><span className="section-kicker">0.0.5-B Wiki</span><h3>Categories</h3></div><p>Content included in the released 0.0.5-B build.</p></div><div className="category-grid">
    <Link className="category-card category-card-image category-card-link" href="/wiki/machines"><div className="category-visual"><Image className="machine-category-image" src="/machines.png" alt="HBM Machines" width={320} height={320} /></div><div className="category-content"><h4>Machines</h4><p>Processing, power, chemistry, foundry, oil and manufacturing machines.</p><span className="category-open">Open wiki →</span></div></Link>
    <Link className="category-card category-card-image category-card-link items-card" href="/wiki/items"><div className="category-visual"><ItemsCube /></div><div className="category-content"><h4>Items</h4><p>Materials, components, equipment, tools, containers and block items.</p><span className="category-open">Open wiki →</span></div></Link>
    <Link className="category-card category-card-image category-card-link fluids-card" href="/wiki/fluids"><div className="category-visual"><FluidOutlineIcon /></div><div className="category-content"><h4>Fluids</h4><p>Chemicals, petrochemicals, gases, coolants and advanced process fluids.</p><span className="category-open">Open wiki →</span></div></Link>
    {["Weapons", "Missiles", "Nuclear Systems"].map(title => <article className="category-card category-card-soon" key={title}><div className="category-visual"><QuestionIcon /></div><div className="category-content"><span className="category-state soon">Coming Soon</span><h4>{title}</h4><p>This section is reserved for a future release and is intentionally not documented as 0.0.5-B content.</p></div></article>)}
  </div></section>
  <section className="guides-section" id="guides"><div className="section-heading"><div><span className="section-kicker">Browse</span><h3>0.0.5-B Wiki</h3></div></div><div className="guide-grid">{quickLinks.map(({ Icon, title, text, href }) => <Link className="guide-card" href={href} key={title}><div className="guide-icon"><Icon /></div><div><h4>{title}</h4><p>{text}</p></div></Link>)}</div></section>
  <section className="community-section"><div><span className="section-kicker">Community</span><h3>Need help or found a bug?</h3><p>Ask questions on Discord or report reproducible issues in the GitHub repository.</p></div><div className="community-actions"><a className="primary-button" href="https://discord.gg/A9NK8xypwU" target="_blank" rel="noreferrer">Discord</a><a className="secondary-button" href="https://github.com/YellowYotu/hbm_neoforge-1.21.1/issues" target="_blank" rel="noreferrer">Bug Reports</a></div></section>
  <footer><div className="footer-brand"><Image src="/logo-main.png" alt="HBM's NTM NeoForge Edition logo" width={80} height={60} /><span>HBM&apos;s Nuclear Tech Mod: Unofficial NeoForge Edition</span></div><p>Original mod by <strong>HbmMods</strong> · NeoForge edition developed by <strong>YellowYotu</strong></p></footer>
</main>; }
